export const countryRegionMapping: { [key: string]: string } = {
  DZA: 'Africa',
  AGO: 'Africa',
  BEN: 'Africa',
  BWA: 'Africa',
  BFA: 'Africa',
  BDI: 'Africa',
  CPV: 'Africa',
  CMR: 'Africa',
  CAF: 'Africa',
  TCD: 'Africa',
  COM: 'Africa',
  COG: 'Africa',
  COD: 'Africa',
  CIV: 'Africa',
  DJI: 'Africa',
  EGY: 'Africa',
  GNQ: 'Africa',
  ERI: 'Africa',
  SWZ: 'Africa',
  ETH: 'Africa',
  GAB: 'Africa',
  GMB: 'Africa',
  GHA: 'Africa',
  GIN: 'Africa',
  GNB: 'Africa',
  KEN: 'Africa',
  LSO: 'Africa',
  LBR: 'Africa',
  LBY: 'Africa',
  MDG: 'Africa',
  MWI: 'Africa',
  MLI: 'Africa',
  MRT: 'Africa',
  MUS: 'Africa',
  MYT: 'Africa',
  MAR: 'Africa',
  MOZ: 'Africa',
  NAM: 'Africa',
  NER: 'Africa',
  NGA: 'Africa',
  REU: 'Africa',
  RWA: 'Africa',
  STP: 'Africa',
  SEN: 'Africa',
  SYC: 'Africa',
  SLE: 'Africa',
  SOM: 'Africa',
  ZAF: 'Africa',
  SSD: 'Africa',
  SDN: 'Africa',
  TZA: 'Africa',
  TGO: 'Africa',
  TUN: 'Africa',
  UGA: 'Africa',
  ZMB: 'Africa',
  ZWE: 'Africa',

  AFG: 'Asia',
  ARM: 'Asia',
  AZE: 'Asia',
  BHR: 'Asia',
  BGD: 'Asia',
  BTN: 'Asia',
  BRN: 'Asia',
  KHM: 'Asia',
  CHN: 'Asia',
  CYP: 'Asia',
  GEO: 'Asia',
  HKG: 'Asia',
  IND: 'Asia',
  IDN: 'Asia',
  IRN: 'Asia',
  IRQ: 'Asia',
  ISR: 'Asia',
  JPN: 'Asia',
  JOR: 'Asia',
  KAZ: 'Asia',
  KWT: 'Asia',
  KGZ: 'Asia',
  LAO: 'Asia',
  LBN: 'Asia',
  MAC: 'Asia',
  MYS: 'Asia',
  MDV: 'Asia',
  MNG: 'Asia',
  MMR: 'Asia',
  NPL: 'Asia',
  PRK: 'Asia',
  OMN: 'Asia',
  PAK: 'Asia',
  PSE: 'Asia',
  PHL: 'Asia',
  QAT: 'Asia',
  SAU: 'Asia',
  SGP: 'Asia',
  KOR: 'Asia',
  LKA: 'Asia',
  SYR: 'Asia',
  TWN: 'Asia',
  TJK: 'Asia',
  THA: 'Asia',
  TLS: 'Asia',
  TUR: 'Asia',
  TKM: 'Asia',
  ARE: 'Asia',
  UZB: 'Asia',
  VNM: 'Asia',
  YEM: 'Asia',

  ALB: 'Europe',
  AND: 'Europe',
  AUT: 'Europe',
  BLR: 'Europe',
  BEL: 'Europe',
  BIH: 'Europe',
  BGR: 'Europe',
  HRV: 'Europe',
  CZE: 'Europe',
  DNK: 'Europe',
  EST: 'Europe',
  FRO: 'Europe',
  FIN: 'Europe',
  FRA: 'Europe',
  DEU: 'Europe',
  GIB: 'Europe',
  GRC: 'Europe',
  GRL: 'Europe',
  HUN: 'Europe',
  ISL: 'Europe',
  IRL: 'Europe',
  ITA: 'Europe',
  LVA: 'Europe',
  LIE: 'Europe',
  LTU: 'Europe',
  LUX: 'Europe',
  MLT: 'Europe',
  MDA: 'Europe',
  MCO: 'Europe',
  MNE: 'Europe',
  NLD: 'Europe',
  MKD: 'Europe',
  NOR: 'Europe',
  POL: 'Europe',
  PRT: 'Europe',
  ROU: 'Europe',
  RUS: 'Europe',
  SMR: 'Europe',
  SRB: 'Europe',
  SVK: 'Europe',
  SVN: 'Europe',
  ESP: 'Europe',
  SWE: 'Europe',
  CHE: 'Europe',
  UKR: 'Europe',
  GBR: 'Europe',
  VAT: 'Europe',

  AIA: 'North America',
  ATG: 'North America',
  BHS: 'North America',
  BRB: 'North America',
  BLZ: 'North America',
  BMU: 'North America',
  VGB: 'North America',
  CAN: 'North America',
  CYM: 'North America',
  CRI: 'North America',
  CUB: 'North America',
  DMA: 'North America',
  DOM: 'North America',
  SLV: 'North America',
  GRD: 'North America',
  GLP: 'North America',
  GTM: 'North America',
  HTI: 'North America',
  HND: 'North America',
  JAM: 'North America',
  MTQ: 'North America',
  MEX: 'North America',
  MSR: 'North America',
  NIC: 'North America',
  PAN: 'North America',
  PRI: 'North America',
  KNA: 'North America',
  LCA: 'North America',
  SPM: 'North America',
  VCT: 'North America',
  TTO: 'North America',
  TCA: 'North America',
  USA: 'North America',

  ASM: 'Oceania',
  AUS: 'Oceania',
  NZL: 'Oceania',
  COK: 'Oceania',
  FJI: 'Oceania',
  PYF: 'Oceania',
  GUM: 'Oceania',
  KIR: 'Oceania',
  MHL: 'Oceania',
  FSM: 'Oceania',
  NRU: 'Oceania',
  NCL: 'Oceania',
  NIU: 'Oceania',
  NFK: 'Oceania',
  MNP: 'Oceania',
  PLW: 'Oceania',
  PNG: 'Oceania',
  WSM: 'Oceania',
  SLB: 'Oceania',
  TKL: 'Oceania',
  TON: 'Oceania',
  TUV: 'Oceania',
  VUT: 'Oceania',
  WLF: 'Oceania',

  ARG: 'South America',
  BOL: 'South America',
  BRA: 'South America',
  CHL: 'South America',
  COL: 'South America',
  ECU: 'South America',
  FLK: 'South America',
  GUF: 'South America',
  GUY: 'South America',
  PRY: 'South America',
  PER: 'South America',
  SUR: 'South America',
  URY: 'South America',
  VEN: 'South America',
};

export const getRegionFromISOCode = (isoCode: string): string => {
  if (!isoCode) return 'Unknown';
  return countryRegionMapping[isoCode] || 'Unknown';
};

export const getAllRegions = (): string[] => {
  const regions = new Set(Object.values(countryRegionMapping));
  return Array.from(regions).sort();
};
